addons:
  apt_packages:
    - lib32z1
    - lib32stdc++6
    - p7zip-full
    - rsync

language: c

sudo: false

env:
  - SOURCEMOD=1.8
  - SOURCEMOD=1.9

script:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash build.sh $SOURCEMOD ${TRAVIS_COMMIT::7}; 